### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [SaltanovskaV/__grid-template#1]
1)
такой синтаксис не принят в html и css - используйте БЭМ 
![image](https://user-images.githubusercontent.com/8464662/122543275-4639c500-d034-11eb-870e-d6aa91beafb6.png)

2)
невалидный стиль
![image](https://user-images.githubusercontent.com/8464662/122543345-59e52b80-d034-11eb-870d-410b1e5379aa.png)

**Comment by Alecto** [comment]
3)
неправильное положение
![image](https://user-images.githubusercontent.com/8464662/122550204-11ca0700-d03c-11eb-986b-279818427ccd.png)

4)
неправильный вид
![image](https://user-images.githubusercontent.com/8464662/122550270-24444080-d03c-11eb-9eaf-47b0c0894e83.png)


5)
меню не работает
![image](https://user-images.githubusercontent.com/8464662/122550352-3a520100-d03c-11eb-9e5f-c5afd3a330bd.png)

6)
неправильное оформление для всех разрешений
![image](https://user-images.githubusercontent.com/8464662/122550430-50f85800-d03c-11eb-8547-b7903976caed.png)

7)
неправильные отступы для всех разрешений
![image](https://user-images.githubusercontent.com/8464662/122550495-653c5500-d03c-11eb-953b-ac88aca29270.png)

**Comment by SaltanovskaV** [comment]
все вроде исправила))

**Comment by Alecto** [comment]
две ссылки пожалуйста

пт, 18 июн. 2021 г. в 21:37, SaltanovskaV ***@***.***>:

**Comment by Alecto** [comment]
проекты так не именуют
![image](https://user-images.githubusercontent.com/8464662/122631836-463ed100-d0d7-11eb-8235-cccdec4b9b1b.png)

если вы хотите конечно его показывать в своем резюме.
только не удаляйте репозиторий, иначе на этом проверка закончится.

**Comment by Alecto** [comment]
6, 7 - не исправлено


8)
неправильный цвет 
![image](https://user-images.githubusercontent.com/8464662/122631852-71292500-d0d7-11eb-83c3-16784fb7e99d.png)


9)
неправильное положение
![image](https://user-images.githubusercontent.com/8464662/122631871-9453d480-d0d7-11eb-8dd7-8bda472be415.png)

**Comment by SaltanovskaV** [comment]
https://github.com/SaltanovskaV/__grid-template
https://saltanovskav.github.io/__grid-template/

уточните пожалуйста 9 пункт работы над ошибками) На каком расширении меню накладывается на заголовок. Что-то я такого не вижу.....

**Comment by Alecto** [comment]
9 - не исправлено

10)
некорректный размер шрифта для всех расширений
![image](https://user-images.githubusercontent.com/8464662/122651130-73bf6500-d13f-11eb-8aaa-8ce3d8742a04.png)

**Comment by Alecto** [comment]
сб, 19 июн. 2021 г. в 17:48, SaltanovskaV ***@***.***>:

> https://github.com/SaltanovskaV/__grid-template
> https://saltanovskav.github.io/__grid-template/
>
> уточните пожалуйста 9 пункт работы над ошибками) На каком расширении меню
> накладывается на заголовок. Что-то я такого не вижу.....
>
  на любом

**Comment by SaltanovskaV** [comment]
https://github.com/SaltanovskaV/__grid-template
https://saltanovskav.github.io/__grid-template/

**Comment by Alecto** [comment]
11)
данное правило избыточно
![image](https://user-images.githubusercontent.com/8464662/122672833-3bb73100-d1d6-11eb-8a51-605d8f90b795.png)

**Comment by SaltanovskaV** [comment]
https://github.com/SaltanovskaV/__grid-template
https://saltanovskav.github.io/__grid-template/

**Comment by Alecto** [comment]
12)
заголовок не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/122761766-4391d680-d2a5-11eb-958f-4e0fad97e253.png)

**Comment by SaltanovskaV** [comment]
https://github.com/SaltanovskaV/__grid-template
https://saltanovskav.github.io/__grid-template/

**Comment by Alecto** [comment]
хорошо, работа принята

пн, 21 июн. 2021 г. в 16:47, SaltanovskaV ***@***.***>:
